#!/usr/bin/python3
#
import subprocess
import sys
import re




def replace(old, new):
	print("%s -> %s" % (old, new))
	subprocess.check_call([ "replaceall", "-R", "-vcn", "-g", "*.py", "-s", "JudgementCode.%s" % (old), "-r", "ExperimentalJudgementCodes.%s" % (new), "x509sak" ])
	subprocess.check_call([ "replaceall", "-R", "-vcn", "-g", "*.py", "-s", "\"%s\"" % (old), "-r", "\"%s\"" % (new), "x509sak" ])
	subprocess.check_call([ "replaceall", "-vcn", "-s", "^([ \t]+%s = )" % (old), "-r", "#\\1", "x509sak/estimate/Judgement.py" ])

old_codes = [ ]
oldre = re.compile("^\s+(?P<id>[_A-Za-z0-9]+) = ")
while True:
	line = input("Line: ")
	result = oldre.match(line)
	if result:
		result = result.groupdict()
		old_codes.append(result["id"])
	if line == ".":
		break


print("Have %d codes" % (len(old_codes)))
for old_code in old_codes:
	new_code = input("%s -> " % (old_code))
	if new_code != "":
		replace(old_code, new_code)
