#!/usr/bin/python3
import re
import math
import subprocess
import collections
import json
import pyasn1.codec.der.decoder
import pyasn1.error
from x509sak import OID

curve_re = re.compile("^  (?P<name>[-a-zA-Z0-9]+)\s*: ")
output = subprocess.check_output([ "openssl", "ecparam", "-list_curves" ]).decode().split("\n")
curves = [ ]
for line in output:
	match = curve_re.match(line)
	if match:
		match = match.groupdict()
		curves.append(match["name"])

_Curve = collections.namedtuple("Curve", [ "oid", "name", "field", "field_size", "order" ])

oid_curves = { }
for curvename in curves:
	domain_params_oid = subprocess.check_output([ "openssl", "ecparam", "-name", curvename, "-outform", "der" ])
	domain_params_explicit = subprocess.check_output([ "openssl", "ecparam", "-name", curvename, "-outform", "der", "-param_enc", "explicit" ])
	try:
		(asn1, tail) = pyasn1.codec.der.decoder.decode(domain_params_oid)
		oid = OID.from_asn1(asn1)

		(asn1, tail) = pyasn1.codec.der.decoder.decode(domain_params_explicit)
		field_type = {
			"1.2.840.10045.1.1":	"prime",
			"1.2.840.10045.1.2":	"binary",
		}[str(asn1[1][0])]
		if field_type == "prime":
			field_size = int(asn1[1][1]).bit_length()
		else:
			field_size = int(asn1[1][1][0])
		order = int(asn1[4])
		curve = _Curve(oid = oid, name = curvename, field = field_type, field_size = field_size, order = order)
		oid_curves[oid] = curve
	except pyasn1.error.PyAsn1Error:
		# OpenSSL bug https://github.com/openssl/openssl/issues/5723
		pass

# Preserve OID order (unnecessary, but pretty)
oid_curves = collections.OrderedDict(sorted(oid_curves.items()))

json_output = collections.OrderedDict()
for (oid, curve) in oid_curves.items():
	json_output[str(oid)] = collections.OrderedDict([
		("name",		curve.name),
		("order_bits",	math.log(float(curve.order), 2)),	# Only an approximation for complexity estimation
		("field",		curve.field),
		("field_size",	curve.field_size),
	])

#for (oid, curve) in sorted(oid_curves.items()):
#	print("		OID.from_str(\"%s\"): \"%s\"," % (oid, curve.name))
print(json.dumps(json_output, indent = 4))
