#!/usr/bin/python3
#	x509sak - The X.509 Swiss Army Knife white-hat certificate toolkit
#	Copyright (C) 2018-2018 Johannes Bauer
#
#	This file is part of x509sak.
#
#	x509sak is free software; you can redistribute it and/or modify
#	it under the terms of the GNU General Public License as published by
#	the Free Software Foundation; this program is ONLY licensed under
#	version 3 of the License, later versions are explicitly excluded.
#
#	x509sak is distributed in the hope that it will be useful,
#	but WITHOUT ANY WARRANTY; without even the implied warranty of
#	MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#	GNU General Public License for more details.
#
#	You should have received a copy of the GNU General Public License
#	along with x509sak; if not, write to the Free Software
#	Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
#
#	Johannes Bauer <JohannesBauer@gmx.de>

import os
import uuid
import shutil
import subprocess

try:
	os.unlink(".coverage")
except FileNotFoundError:
	pass
try:
	shutil.rmtree("htmlcov")
except FileNotFoundError:
	pass
try:
	shutil.rmtree(".coverage_files")
except FileNotFoundError:
	pass
os.mkdir(".coverage_files")

cwd = os.path.realpath(".")
os.environ["COVERAGE_FILE"] = cwd + "/.coverage_files/" + str(uuid.uuid4())
subprocess.check_call([ "coverage", "run", "--omit", "/usr/*", "./run_tests.py", "--coverage" ])

files = [ ".coverage_files/%s" % (filename) for filename in os.listdir(".coverage_files") ]

os.environ["COVERAGE_FILE"] = cwd + "/.coverage"
subprocess.check_call([ "coverage", "combine" ] + files)
shutil.rmtree(".coverage_files")

subprocess.check_call([ "coverage", "html" ])
subprocess.check_call([ "chromium-browser", "htmlcov/index.html" ])

