#!/usr/bin/python3
import re
import math
import subprocess
import collections
import json
import pyasn1.codec.der.decoder
import pyasn1.error
from x509sak import OID

curve_re = re.compile("^  (?P<name>[-a-zA-Z0-9]+)\s*: ")
output = subprocess.check_output([ "openssl", "ecparam", "-list_curves" ]).decode().split("\n")
curves = [ ]
for line in output:
	match = curve_re.match(line)
	if match:
		match = match.groupdict()
		curves.append(match["name"])

_Curve = collections.namedtuple("Curve", [ "oid", "name", "field", "domain" ])

oid_curves = { }
for curvename in curves:
	domain_params_oid = subprocess.check_output([ "openssl", "ecparam", "-name", curvename, "-outform", "der" ])
	domain_params_explicit = subprocess.check_output([ "openssl", "ecparam", "-name", curvename, "-outform", "der", "-param_enc", "explicit" ])
	try:
		(asn1, tail) = pyasn1.codec.der.decoder.decode(domain_params_oid)
		oid = OID.from_asn1(asn1)

		(asn1, tail) = pyasn1.codec.der.decoder.decode(domain_params_explicit)
		field_type = {
			"1.2.840.10045.1.1":	"prime",
			"1.2.840.10045.1.2":	"binary",
		}[str(asn1[1][0])]

		if field_type == "prime":
			domain = collections.OrderedDict([
				("p", int(asn1[1][1])),
			])
		else:
			basis_type = {
				"1.2.840.10045.1.2.3.1":	"gnBasis",
				"1.2.840.10045.1.2.3.2":	"tpBasis",
				"1.2.840.10045.1.2.3.3":	"ppBasis",
			}[str(asn1[1][1][1])]
			domain = collections.OrderedDict([
				("m", int(asn1[1][1][0])),
			])
			if basis_type == "ppBasis":
				values = [ int(x) for x in asn1[1][1][2] ]
				poly = [ domain["m"] ] + list(reversed(sorted(values))) + [ 0 ]
			elif basis_type == "tpBasis":
				value = int(asn1[1][1][2])
				poly = [ domain["m"], value, 0 ]
			else:
				raise Exception(NotImplemented, basis_type)

			domain["poly"] = poly

		G = bytes(asn1[3])
		assert(G[0] == 0x04)
		assert((len(G) % 2) == 1)
		Glen = len(G) // 2
		Gx = int.from_bytes(G[1 : 1 + Glen], byteorder = "big")
		Gy = int.from_bytes(G[1 + Glen : 1 + (2 * Glen)], byteorder = "big")
		domain["a"] = int.from_bytes(asn1[2][0], byteorder = "big")
		domain["b"] = int.from_bytes(asn1[2][1], byteorder = "big")
		domain["Gx"] = Gx
		domain["Gy"] = Gy
		domain["n"] = int(asn1[4])
		domain["h"] = int(asn1[5])

		curve = _Curve(oid = oid, name = curvename, field = field_type, domain = domain)
		oid_curves[oid] = curve
	except pyasn1.error.PyAsn1Error:
		# OpenSSL bug https://github.com/openssl/openssl/issues/5723
		pass
#	break

# Preserve OID order (unnecessary, but pretty)
oid_curves = collections.OrderedDict(sorted(oid_curves.items()))

json_output = collections.OrderedDict()
for (oid, curve) in oid_curves.items():
	json_output[str(oid)] = collections.OrderedDict([
		("name",		curve.name),
		("field",		curve.field),
		("domain",		curve.domain),
	])

#for (oid, curve) in sorted(oid_curves.items()):
#	print("		OID.from_str(\"%s\"): \"%s\"," % (oid, curve.name))
print(json.dumps(json_output, indent = 4))
