/*
 *   This file was AUTO-GENERATED by pypgmopts.
 *
 *   https://github.com/johndoe31415/pypgmopts
 *
 *   Do not edit it by hand, your changes will be overwritten.
 *
 *   Generated at: 2020-01-06 10:38:00
 */

#ifndef __ARGPARSE_H__
#define __ARGPARSE_H__

#include <stdbool.h>

#define ARGPARSE_DEFAULT_MODE		"random"
#define ARGPARSE_DEFAULT_PRIME_TYPE		"2msb"
#define ARGPARSE_DEFAULT_THREAD_CNT		8
#define ARGPARSE_DEFAULT_BIT_LENGTH		2048
#define ARGPARSE_DEFAULT_NUM_PRIMES		10

#define ARGPARSE_NO_OPTION		0
#define ARGPARSE_POSITIONAL_ARG	1

enum argparse_option_t {
	ARG_MODE = 2,
	ARG_PRIME_TYPE = 3,
	ARG_THREAD_CNT = 4,
	ARG_BIT_LENGTH = 5,
	ARG_NUM_PRIMES = 6,
};

typedef void (*argparse_errmsg_callback_t)(const char *errmsg, ...);
typedef void (*argparse_errmsg_option_callback_t)(enum argparse_option_t error_option, const char *errmsg, ...);
typedef bool (*argparse_callback_t)(enum argparse_option_t option, const char *value, argparse_errmsg_callback_t errmsg_callback);
typedef bool (*argparse_plausibilization_callback_t)(argparse_errmsg_option_callback_t errmsg_callback);

bool argparse_parse(int argc, char **argv, argparse_callback_t argument_callback, argparse_plausibilization_callback_t plausibilization_callback);
void argparse_show_syntax(void);
void argparse_parse_or_quit(int argc, char **argv, argparse_callback_t argument_callback, argparse_plausibilization_callback_t plausibilization_callback);

#endif
