#!/usr/bin/env python3
#	x509sak - The X.509 Swiss Army Knife white-hat certificate toolkit
#	Copyright (C) 2018-2018 Johannes Bauer
#
#	This file is part of x509sak.
#
#	x509sak is free software; you can redistribute it and/or modify
#	it under the terms of the GNU General Public License as published by
#	the Free Software Foundation; this program is ONLY licensed under
#	version 3 of the License, later versions are explicitly excluded.
#
#	x509sak is distributed in the hope that it will be useful,
#	but WITHOUT ANY WARRANTY; without even the implied warranty of
#	MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#	GNU General Public License for more details.
#
#	You should have received a copy of the GNU General Public License
#	along with x509sak; if not, write to the Free Software
#	Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
#
#	Johannes Bauer <JohannesBauer@gmx.de>

import os

dirname = os.path.dirname(__file__) + "/../x509sak/tests/data/certs/x509test/"
for filename in sorted(os.listdir(dirname)):
	if not filename.startswith("xf-"):
		continue
	if not filename.endswith(".pem"):
		continue

	fnname = "test_examine_x509test_" + filename.replace("-", "_")[:-4]
	print("#	def %s(self):" % (fnname))
	print("#		self._test_examine_x509test_resultcode(\"certs/x509test/%s\", \"\")" % (filename))
	print("#		self._test_examine_x509test_noparse(\"certs/x509test/%s\")" % (filename))
	print("#")
