#!/usr/bin/python3
#	x509sak - The X.509 Swiss Army Knife white-hat certificate toolkit
#	Copyright (C) 2020-2020 Johannes Bauer
#
#	This file is part of x509sak.
#
#	x509sak is free software; you can redistribute it and/or modify
#	it under the terms of the GNU General Public License as published by
#	the Free Software Foundation; this program is ONLY licensed under
#	version 3 of the License, later versions are explicitly excluded.
#
#	x509sak is distributed in the hope that it will be useful,
#	but WITHOUT ANY WARRANTY; without even the implied warranty of
#	MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#	GNU General Public License for more details.
#
#	You should have received a copy of the GNU General Public License
#	along with x509sak; if not, write to the Free Software
#	Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
#
#	Johannes Bauer <JohannesBauer@gmx.de>

exts = [ "AKI", "BC", "CP", "CRLDP", "EKU", "IAN", "KU", "NC", "NSCT", "SAN", "SKI" ]
#exts += [ "PC" ]
for ext in sorted(exts):
	for errtype in [ "malformed", "wrong_type", "non_der", "trailing_data" ]:
		filename = "certs/generated/ext_%s_%s.pem" % (ext, errtype)
		suffix = {
			"malformed":		"Malformed_Undecodable",
			"wrong_type":		"Malformed_UnexpectedType",
			"non_der":			"Malformed_NonDEREncoding",
			"trailing_data":	"TrailingData",
		}[errtype]
		code = "X509Cert_Body_X509Exts_Ext_%s_%s" % (ext, suffix)
		print("	def test_generated_extension_%s_%s(self):" % (ext, errtype))
		print("		self._test_examine_x509test_resultcode(\"%s\", expect_present = \"%s\")" % (filename, code))
		print()
