#!/usr/bin/python3
#
import subprocess
import sys

def replace(old, new):
	print("%s -> %s" % (old, new))
	subprocess.check_call([ "replaceall", "-R", "-vcn", "-g", "*.py", "-s", "ExperimentalJudgementCodes.%s" % (old), "-r", "ExperimentalJudgementCodes.%s" % (new), "x509sak" ])
	subprocess.check_call([ "replaceall", "-R", "-vcn", "-g", "*.py", "-s", "\"%s\"" % (old), "-r", "\"%s\"" % (new), "x509sak" ])

if len(sys.argv) == 3:
	(old, new) = sys.argv[1:]
	replace(old, new)
else:
	print("%s [old name] [new name]" % (sys.argv[0]))
