#!/usr/bin/python3
#
import subprocess
import sys

def replace(old, new):
	print("%s -> %s" % (old, new))
	subprocess.check_call([ "replaceall", "-R", "-vcn", "-g", "*.py", "-s", "JudgementCode.%s" % (old), "-r", "JudgementCode.%s" % (new), "x509sak" ])
	subprocess.check_call([ "replaceall", "-R", "-vcn", "-g", "*.py", "-s", "\"%s\"" % (old), "-r", "\"%s\"" % (new), "x509sak" ])

if len(sys.argv) == 3:
	(old, new) = sys.argv[1:]
	replace(old, new)
else:
	print("Bulk refactor mode entered.")
	while True:
		line = input("Old and new: ")
		line = line.split()
		if len(line) == 2:
			(old, new) = line
			replace(old, new)
		else:
			print("Invalid entry.")
