#!/usr/bin/python3
#	x509sak - The X.509 Swiss Army Knife white-hat certificate toolkit
#	Copyright (C) 2019-2019 Johannes Bauer
#
#	This file is part of x509sak.
#
#	x509sak is free software; you can redistribute it and/or modify
#	it under the terms of the GNU General Public License as published by
#	the Free Software Foundation; this program is ONLY licensed under
#	version 3 of the License, later versions are explicitly excluded.
#
#	x509sak is distributed in the hope that it will be useful,
#	but WITHOUT ANY WARRANTY; without even the implied warranty of
#	MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#	GNU General Public License for more details.
#
#	You should have received a copy of the GNU General Public License
#	along with x509sak; if not, write to the Free Software
#	Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
#
#	Johannes Bauer <JohannesBauer@gmx.de>

import sys
import sqlite3
import contextlib
import os
import subprocess
from x509sak.FriendlyArgumentParser import FriendlyArgumentParser

parser = FriendlyArgumentParser(description = "Examine results of a test corpus run.")
parser.add_argument("-d", "--dbfile", metavar = "filename", type = str, default = "test_corpus_results.sqlite3", help = "Specifies database file which stores the scraping results. Defaults to %(default)s.")
parser.add_argument("-o", "--outdir", metavar = "path", type = str, default = "test_corpus_failures", help = "Specifies output file to write failed certificates to. Defaults to %(default)s.")
args = parser.parse_args(sys.argv[1:])

with contextlib.suppress(FileExistsError):
	os.makedirs(args.outdir)

db = sqlite3.connect(args.dbfile)
cursor = db.cursor()
(total_results, ) = cursor.execute("SELECT COUNT(*) FROM test_results;").fetchone()
(failed_results, ) = cursor.execute("SELECT COUNT(*) FROM test_results WHERE returncode != 0;").fetchone()
print("Found %d results total, %d which failed." % (total_results, failed_results))

for row in cursor.execute("SELECT certs_key_sha256, returncode, stdout, stderr, cert_der, ca_cert_der, cert_usage, cert_fqdn FROM test_results WHERE returncode != 0 ORDER BY id ASC;").fetchall():
	(certs_key_sha256, returncode, stdout, stderr, cert_der, ca_cert_der, cert_usage, cert_fqdn) = row
	usage_fqdn = "%s/%s" % (cert_fqdn, cert_usage)
	print("%-60s returncode %d" % (usage_fqdn, returncode))
	outfile_pem = args.outdir + "/" + certs_key_sha256.hex() + ".pem"
	outfile_ca_pem = args.outdir + "/" + certs_key_sha256.hex() + "_ca.pem"
	outfile_txt = args.outdir + "/" + certs_key_sha256.hex() + ".txt"
	with open(outfile_txt, "w") as f:
		print("Usage     : %s" % (cert_usage), file = f)
		print("FQDN      : %s" % (cert_fqdn), file = f)
		print("Returncode: %d" % (returncode), file = f)
		print("Commandline:", file = f)
		cmd = [ "./x509sak.py", "examine" ]
		cmd += [ "-p", cert_usage ]
		if cert_fqdn is not None:
			cmd += [ "--server-name=%s" % (cert_fqdn) ]
		if ca_cert_der is not None:
			cmd += [ "-r", outfile_ca_pem ]
		cmd += [ outfile_pem ]
		print(" ".join(cmd), file = f)
		print(file = f)
		print("=" * 120, file = f)
		print(file = f)
		print("stdout:", file = f)
		print(stdout.decode(), file = f)
		print(file = f)
		print("=" * 120, file = f)
		print(file = f)
		print("stderr:", file = f)
		print(stderr.decode(), file = f)
	subprocess.check_output([ "openssl", "x509", "-inform", "der", "-out", outfile_pem ], input = cert_der)
	if ca_cert_der is not None:
		subprocess.check_output([ "openssl", "x509", "-inform", "der", "-out", outfile_ca_pem ], input = ca_cert_der)
